Traceback (most recent call last):
  File "Experiment1.py", line 3, in <module>
    sp.call(["energyplus", "-w","USA_CO_Golden-NREL.724666_TMY3.epw", "-r","1ZoneUncontrolled.idf"])
  File "/scratch/user/ffeng/programs/anaconda3/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/scratch/user/ffeng/programs/anaconda3/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/scratch/user/ffeng/programs/anaconda3/lib/python3.8/subprocess.py", line 1706, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'energyplus'
